version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
     - "8081:80"   # obecny HTTP
     - "8443:443"  # dodaj HTTPS dla localhost

    volumes:
      - .:/app/
      - ./storage/uploads:/app/storage/uploads
    links:
      - php
    networks:
      - pg-network
  
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "5434:5432"
    networks:
      - pg-network
  
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app
      - ./storage/uploads:/app/storage/uploads
    networks:
      - pg-network
  
  pgadmin-wdpai:
    image: dpage/pgadmin4:latest
    container_name: pg-admin2_0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    networks:
      - pg-network
  
networks:
  pg-network:

volumes:
  pg-data: